#!/usr/bin/env python3
import sys
import os

from ament_index_python.packages import get_package_share_directory

package_share = get_package_share_directory('tennisbuddy_perception')
src_path = os.path.join(package_share, 'src')
if src_path not in sys.path:
    sys.path.insert(0, src_path)

from perception.nodes.ball_spawner import main

if __name__ == '__main__':
    main()

