# Base Dockerfile - Common ROS2 environment
# This is the base image for both Gazebo and node containers
# syntax=docker/dockerfile:1

ARG UBUNTU_VERSION=22.04
ARG ROS_DISTRO=humble
FROM ubuntu:${UBUNTU_VERSION} AS base

ARG ROS_DISTRO
ENV DEBIAN_FRONTEND=noninteractive
ENV LANG=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8
ENV ROS_DISTRO=${ROS_DISTRO}

############################
# Basic dependencies
############################
RUN apt-get update && apt-get install -y \
    locales sudo software-properties-common \
    curl wget git gnupg2 lsb-release \
    python3-pip python3-venv apt-transport-https \
    net-tools iproute2 \
    && locale-gen en_US.UTF-8

############################
# ROS 2 + launch
############################
RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key \
    -o /usr/share/keyrings/ros-archive-keyring.gpg && \
    echo "deb [signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] \
    http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" \
    > /etc/apt/sources.list.d/ros2.list

RUN apt-get update && apt-get install -y \
    ros-${ROS_DISTRO}-ros-base \
    ros-${ROS_DISTRO}-launch \
    ros-${ROS_DISTRO}-launch-ros \
    ros-${ROS_DISTRO}-slam-toolbox \
    ros-${ROS_DISTRO}-navigation2 \
    ros-${ROS_DISTRO}-nav2-bringup \
    ros-${ROS_DISTRO}-robot-localization \
    ros-${ROS_DISTRO}-robot-state-publisher \
    ros-${ROS_DISTRO}-joint-state-publisher \
    ros-${ROS_DISTRO}-xacro \
    ros-${ROS_DISTRO}-joy-linux \
    python3-colcon-common-extensions \
    && rm -rf /var/lib/apt/lists/*

RUN echo "source /opt/ros/${ROS_DISTRO}/setup.bash" >> /etc/bash.bashrc

WORKDIR /workspace/tennisbuddy

# Copy workspace (will be overridden in child images)
COPY .. /workspace/tennisbuddy

# Build workspace
RUN source /opt/ros/${ROS_DISTRO}/setup.bash && \
    cd /workspace/tennisbuddy && \
    colcon build --symlink-install || true

ENTRYPOINT ["/bin/bash"]
